import { html } from 'lit';

export const labels = {
	EN: {
		period: 'Period',
		start: 'Start',
		end: 'End',
		source: 'Source',
		price: 'price',
		emptyMessage: "You haven't used Intrinsic yet",
		per: 'P / E',
		p_bv: 'P / BV',
		ev: 'EV',
		ev_cap: html`EV<sub>cap</sub>`,
		ev_cfo: html`EV / CF<sub>op</sub>`,
		ev_net_income: 'EV / π',
		current_assets: 'CA',
		non_current_assets: 'NCA',
		total_assets: 'TA',
		cash_and_equivalents: 'Cash',
		current_liabilities: 'CL',
		non_current_liabilities: 'NCL',
		total_liabilities: 'TL',
		equity: 'E',
		working_capital: 'WC',
		wc_ncl: 'WC / NCL',
		shares: html`Shares<sub>≈</sub>`,
		book_value: 'BV',
		revenue: 'R',
		net_income: 'π',
		eps: 'EPS',
		net_margin: html`M<sub>net</sub>`,
		roa: 'ROA',
		roe: 'ROE',
		liquidity: 'Liquidity',
		solvency: 'Solvency',
		leverage: 'Leverage',
		cash_flow_from_operations: html`CF<sub>op</sub>`,
		cash_flow_from_investing: html`CF<sub>inv</sub>`,
		cash_flow_from_financing: html`CF<sub>fin</sub>`,
		score: 'Score',
		nuke1: 'You are about to nuke your Intrisic data',
		nuke2: 'IRREVERSIBLE ACTION',
		vNeedsUpdate: 'Update to',
		vDoesntNeedUpdate: 'Using latest version',
	},

	ES: {
		period: 'Periodo',
		start: 'Inicio',
		end: 'Fin',
		source: 'Fuente',
		price: 'precio',
		emptyMessage: 'Todavía no has usado Intrinsic',
		per: 'P / E',
		p_bv: 'P / BV',
		ev: 'EV',
		ev_cap: html`EV<sub>cap</sub>`,
		ev_cfo: html`EV / CF<sub>op</sub>`,
		ev_net_income: 'EV / π',
		current_assets: 'AC',
		non_current_assets: 'ANC',
		total_assets: 'AT',
		cash_and_equivalents: 'Cash',
		current_liabilities: 'PC',
		non_current_liabilities: 'PNC',
		total_liabilities: 'PT',
		equity: 'PN',
		working_capital: 'FM',
		wc_ncl: 'FM / PNC',
		shares: html`Acciones<sub>≈</sub>`,
		book_value: 'BV',
		revenue: 'I',
		net_income: 'π',
		eps: 'BPA',
		net_margin: html`M<sub>net</sub>`,
		roa: 'ROA',
		roe: 'ROE',
		liquidity: 'Liquidez',
		solvency: 'Solvencia',
		leverage: 'Apalancamiento',
		cash_flow_from_operations: html`CF<sub>op</sub>`,
		cash_flow_from_investing: html`CF<sub>inv</sub>`,
		cash_flow_from_financing: html`CF<sub>fin</sub>`,
		score: 'Score',
		nuke1: 'Estás a punto de eliminar tus datos de Intrisic',
		nuke2: 'ACCIÓN IRREVERSIBLE',
		vNeedsUpdate: 'Actualiza a',
		vDoesntNeedUpdate: 'Usando última versión',
	},
};

export function getFinancesLabels(lang) {
	const t = labels[lang];
	return [
		{ label: t.per, field: 'per', format: 'float', source: 'derivedRatios' },
		{ label: t.p_bv, field: 'p_bv', format: 'float', source: 'derivedRatios' },
		{ label: t.ev, field: 'ev', format: 'int', source: 'derivedRatios' },
		{
			label: t.ev_cap,
			field: 'ev_cap',
			format: 'float',
			source: 'derivedRatios',
		},
		{
			label: t.ev_cfo,
			field: 'ev_cfo',
			format: 'float',
			source: 'derivedRatios',
		},
		{
			label: t.ev_net_income,
			field: 'ev_net_income',
			format: 'float',
			source: 'derivedRatios',
		},

		{
			label: t.current_assets,
			field: 'current_assets',
			format: 'int',
			source: 'data',
		},
		{
			label: t.non_current_assets,
			field: 'non_current_assets',
			format: 'int',
			source: 'data',
		},
		{
			label: t.total_assets,
			field: 'total_assets',
			format: 'int',
			source: 'data',
		},
		{
			label: t.cash_and_equivalents,
			field: 'cash_and_equivalents',
			format: 'int',
			source: 'data',
		},
		{
			label: t.current_liabilities,
			field: 'current_liabilities',
			format: 'int',
			source: 'data',
		},
		{
			label: t.non_current_liabilities,
			field: 'non_current_liabilities',
			format: 'int',
			source: 'data',
		},
		{
			label: t.total_liabilities,
			field: 'total_liabilities',
			format: 'int',
			source: 'data',
		},
		{ label: t.equity, field: 'equity', format: 'int', source: 'data' },
		{
			label: t.working_capital,
			field: 'working_capital',
			format: 'int',
			source: 'data',
		},
		{ label: t.wc_ncl, field: 'wc_ncl', format: 'float', source: 'data' },
		{ label: t.shares, field: 'shares', format: 'int', source: 'data' },
		{
			label: t.book_value,
			field: 'book_value',
			format: 'float',
			source: 'data',
		},

		{ label: t.revenue, field: 'revenue', format: 'int', source: 'data' },
		{ label: t.net_income, field: 'net_income', format: 'int', source: 'data' },
		{ label: t.eps, field: 'eps', format: 'float', source: 'data' },
		{
			label: t.net_margin,
			field: 'net_margin',
			format: 'percent',
			source: 'data',
		},
		{ label: t.roa, field: 'roa', format: 'percent', source: 'data' },
		{ label: t.roe, field: 'roe', format: 'percent', source: 'data' },

		{ label: t.liquidity, field: 'liquidity', format: 'float', source: 'data' },
		{ label: t.solvency, field: 'solvency', format: 'float', source: 'data' },
		{ label: t.leverage, field: 'leverage', format: 'float', source: 'data' },

		{
			label: t.cash_flow_from_operations,
			field: 'cash_flow_from_operations',
			format: 'int',
			source: 'data',
		},
		{
			label: t.cash_flow_from_investing,
			field: 'cash_flow_from_investing',
			format: 'int',
			source: 'data',
		},
		{
			label: t.cash_flow_from_financing,
			field: 'cash_flow_from_financing',
			format: 'int',
			source: 'data',
		},

		{
			label: t.score,
			field: 'score',
			format: 'float',
			source: 'derivedRatios',
		},
	];
}
