export const WINDOW_SIZE = 10000;
export const OVERLAP_STRIDE = WINDOW_SIZE / 3;
export const BUFFER_SIZE = 1000;
export const OUTPUT_CHUNK_SIZE = 12000;

export const balanceIndicators = new Set([
	'assets',
	'liabilities',
	'current assets',
	'total current assets',
	'total assets',
	'total non-current assets',
	'receivables',
	'current liabilities',
	'ordinary share',
	'marketable securities',
	'total current liabilities',
	'total liabilities',
	'total non-current liabilities',
	'non-current',
	'continuing',
	'non-current financial',
	'non-current assets',
	'non-current liabilities',
	'financing liabilities',
	"shareholders' equity",
	"stockholders' equity",
	'total equity',
	'liabilities and equity',
	'equity and liabilities',
	'total liabilities and equity',
	'total equity and liabilities',
	'equity',
	'cash equivalents',
	'cash and cash equivalents',
	'cash and',
	'fixed assets',
	'unearned revenue',
	'accounts receivable',
	'lease',
	'net assets',
	'lease liabilities',
	'inventories',
	'property, plant',
	'taxes receivable',
	'tax receivable',
	'assets classified',
	'other receivables',
	'property',
	'goodwill',
	'intangible assets',
	'payable',
	'accounts payable',
	'accrued liabilities',
	'accrued expenses',
	'accrued compensation',
	'accrued payroll',
	'short-term debt',
	'short-term investments',
	'investments accounted',
	'long-term debt',
	'long-term assets',
	'long-term liabilities',
	'long-term investments',
	'other long-term',
	'right-of-use',
	'deferred revenue',
	'deferred income',
	'provision',
	'deferred tax',
	'capital',
	'other assets',
	'other current assets',
	'other non-current assets',
	'other liabilities',
	'other current liabilities',
	'other non-current liabilities',
	'financial asset',
	'financial liabilit',
	'common stock',
	'retained earnings',
	"shareholders' deficit",
	"stockholders' equity",
	'total stockholder',
	'total shareholder',
	"shareholders' equity",
	'liabilities and equity',
	"liabilities and stockholders' equity",
	"liabilities and shareholders' equity",
	'treasury stock',
	'treasury shares',
	'(deficit)',
	'consolidated balance',
	'consolidated statement of financial',
	'consolidated financial statement',
	'financial statement',
	'balance sheet',
	'group balance',
	'statement of financial position',
	'months ended',
	'years ended',
	'year ended',
	'gaap',
	'noncontrolling interest',
	'non-controlling interest',
	'audited',
	'in thousand',
	'in million',
	'thousands of',
	'millions of',
	'note',
	'paid-in capital',
	'preferred',
	'prepaid',
	'except per share',
	'share premium',
	'capital stock',
	'retain',
	'cummulative',
	'derivative',
	'loans',
	'prepayments',
	'held for sale',
]);

export const incomeIndicators = new Set([
	'revenue',
	'operating revenue',
	'operating margin',
	'continuing operation',
	'continuing',
	'discontinued',
	'operating cost',
	'cost of revenue',
	'cost of sales',
	'cost of goods',
	'gross profit',
	'gross margin',
	'sales',
	'operating income',
	'marketing',
	'income',
	'income from operations',
	'operating expenses',
	'operating profit',
	'net income',
	'net profit',
	'net earnings',
	'net loss',
	'net sale',
	'ebitda',
	'ebitda margin',
	'foreign exchange',
	'foreign currency',
	'income before tax',
	'tax',
	'income tax',
	'before tax',
	'selling general',
	'profit before',
	'research',
	'interest expense',
	'interest income',
	'other income',
	'administrative',
	'depreciation',
	'amortization',
	'amortisation',
	'earnings per',
	'earnings (loss) per',
	'loss per',
	'per ordinary share',
	'ordinary shareholder',
	'eps',
	'eps attributable',
	'basic',
	'basic earnings per',
	'basic eps',
	'basic net income',
	'diluted',
	'diluted earnings per',
	'diluted eps',
	'diluted net income',
	'share',
	'attributable to common',
	'attributable to owners',
	'noncontrolling interest',
	'non-controlling interest',
	'attributable to',
	'shareholders',
	'common share',
	'weighted',
	'earnings',
	'statements of income',
	'statement of income',
	'income statement',
	'consolidated statements of income',
	'consolidated income statement',
	'income statement',
	'consolidated statements of operations',
	'statement of comprehensive income',
	'comprehensive',
	'statements of operations',
	'statement of operations',
	'audited',
	'in thousand',
	'in million',
	'thousands of',
	'millions of',
	'months ended',
	'years ended',
	'year ended',
	'gaap',
	'parent',
	'note',
	'except per share',
]);

export const cashFlowIndicators = new Set([
	'cash flow from operating',
	'cash flow from operations',
	'cash flows from operating',
	'cash flows from operations',
	'cash flow from investment',
	'cash flow from investing',
	'cash flows from investment',
	'cash flows from investing',
	'cash flow from financing',
	'cash flows from financing',
	'lease',
	'payable',
	'loss',
	'redemption',
	'inventories',
	'unrealized',
	'operating activities',
	'operating activity',
	'investing activities',
	'investing activity',
	'financing activities',
	'financing activity',
	'flows from operations',
	'flow from operations',
	'flows from operating',
	'flows from investment',
	'flow from investing',
	'flows from financing',
	'flow from financing',
	'held for',
	'net cash',
	'cash outflow',
	'cash inflow',
	'before tax',
	'net cash flow',
	'net cash generated',
	'net cash provided',
	'net cash used',
	'reconcile',
	'reconciliation',
	'operating profit',
	'continuing',
	'discontinued',
	'cash',
	'accrued liabilities',
	'cash equivalents',
	'capital expenditures',
	'capex',
	'proceeds from issuance',
	'proceeds from issue',
	'purchase of property',
	'purchases of property',
	'property, plant',
	'property and equipment',
	'purchase of equipment',
	'purchases of equipment',
	'purchases of other',
	'marketable securities',
	'foreign exchange',
	'foreign currency',
	'acquisitions',
	'debt payments',
	'dividend',
	'repurchase',
	'working capital',
	'operating assets',
	'operating liabilities',
	'depreciation',
	'right-of-use',
	'impairment',
	'provision',
	'amortization',
	'amortisation',
	'interest received',
	'interest paid',
	'deferred income',
	'deferred revenue',
	'deferred commissions',
	'intangible',
	'acquisition',
	'operating lease',
	'consolidated statements of cash flow',
	'statements of cash flow',
	'statement of cash flow',
	'audited',
	'gaap',
	'in thousand',
	'in million',
	'thousands of',
	'millions of',
	'changes in',
	'accounts receivable',
	'accounts payable',
	'tax',
	'other',
	'exchange rate',
	'months ended',
	'years ended',
	'year ended',
	'compensation',
	'prepaid',
	'cash, cash equivalents',
	'stock options',
	'note',
	'except per share',
]);
